import { contextBridge, ipcRenderer } from 'electron';
const api = {
    startLanDiscovery: () => ipcRenderer.invoke('lan-discovery-start'),
    stopLanDiscovery: () => ipcRenderer.invoke('lan-discovery-stop'),
    onLanDiscoveryFound: (cb) => ipcRenderer.on('lan-discovery:found', (_e, server) => cb(server)),
    onLanDiscoveryLost: (cb) => ipcRenderer.on('lan-discovery:lost', (_e, server) => cb(server)),
    getClientId: () => ipcRenderer.invoke('get-client-id'),
    maximizeWindow: () => ipcRenderer.invoke('window:maximize'),
    hostServerStart: (options) => ipcRenderer.invoke('host-server-start', options),
    hostServerStop: () => ipcRenderer.invoke('host-server-stop'),
    hostServerStatus: () => ipcRenderer.invoke('host-server-status'),
    getDesktopSources: () => ipcRenderer.invoke('get-desktop-sources'),
    selectImageDialog: () => ipcRenderer.invoke('dialog-select-image'),
    selectSoundboardFolder: () => ipcRenderer.invoke('dialog-select-soundboard-folder'),
    listSoundboardSounds: (folderPath) => ipcRenderer.invoke('soundboard-list-sounds', folderPath),
    readSoundboardSound: (filePath) => ipcRenderer.invoke('soundboard-read-sound', filePath),
    minimize: () => ipcRenderer.invoke('window-minimize'),
    maximize: () => ipcRenderer.invoke('window-maximize'),
    close: () => ipcRenderer.invoke('window-close'),
    getAppVersion: () => ipcRenderer.invoke('get-app-version'),
    checkForUpdates: () => ipcRenderer.invoke('update-check'),
    downloadUpdate: () => ipcRenderer.invoke('update-download'),
    installUpdate: () => ipcRenderer.invoke('update-install'),
    onUpdateProgress: (cb) => ipcRenderer.on('update:progress', (_e, percent) => cb(percent)),
    onUpdateDownloaded: (cb) => ipcRenderer.on('update:downloaded', (_e, info) => cb(info)),
    onUpdateError: (cb) => ipcRenderer.on('update:error', (_e, message) => cb(message)),
    openExternal: (url) => ipcRenderer.invoke('open-external', url),
    probeServer: (host, port) => ipcRenderer.invoke('probe-server', host, port),
    screenAudioSupported: () => ipcRenderer.invoke('screen-audio-supported'),
    screenAudioStart: () => ipcRenderer.invoke('screen-audio-start'),
    screenAudioStop: () => ipcRenderer.invoke('screen-audio-stop'),
    onScreenAudioFrame: (cb) => ipcRenderer.on('screen-audio:frame', (_e, buffer) => cb(buffer)),
    removeScreenAudioFrameListener: () => ipcRenderer.removeAllListeners('screen-audio:frame'),
    platform: process.platform,
};
contextBridge.exposeInMainWorld('api', api);
//# sourceMappingURL=preload.js.map